#!/usr/bin/with-contenv sh

# running as root because "The exec driver can only be run when on Linux and running Nomad as root."
# See: https://www.nomadproject.io/docs/drivers/exec.html
exec nomad agent -config /etc/nomad/conf.d/;
